package ch.unige.idsi15.swisstoolapp;

import ch.unige.idsi15.swisstoolapp.MainActivity;

/*MySql JDBC*/
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;

import ch.unige.idsi15.swisstoolapp.R;
import android.support.v4.app.Fragment;
import android.os.Bundle;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Toast;

import com.google.android.gms.maps.*;
import com.google.android.gms.maps.model.*;

public class MyPlacesFragment extends Fragment {
	
	MapView mMapView;
	private GoogleMap googleMap;
	
	//Specifications pour la conection à la base de données
	private static final String url = "jdbc:mysql://us-cdbr-iron-east-02.cleardb.net:3306/ad_28963a515d51815";
    private static final String user = "b76c1913ef8b0d";
    private static final String pass = "bb35e718";
	public MyPlacesFragment(){}
	
	@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
            Bundle savedInstanceState) {
		/*Initialize map, like in mainactivity*/
				View v  = inflater.inflate(R.layout.fragment_myplaces, container, false);
			    mMapView = (MapView) v.findViewById(R.id.mapView);
			    mMapView.onCreate(savedInstanceState);
			    mMapView.onResume();
			    try {
			    	MapsInitializer.initialize(getActivity().getApplicationContext());
			    } catch (Exception e) {
			    	e.printStackTrace();
			    }
			    googleMap = mMapView.getMap();
			    
			    /*Call for the method who will retrive information from DB, when QrCodeId as parameter asked from the MainActivity*/
			    markersCollector(MainActivity.getQrCodeId());
			    return v;
    }
	
	@Override
	public void onResume() {
	    super.onResume();
	    mMapView.onResume();
	}

	@Override
	public void onPause() {
	    super.onPause();
	    mMapView.onPause();
	}

	@Override
	public void onDestroy() {
	    super.onDestroy();
	    mMapView.onDestroy();
	}

	@Override
	public void onLowMemory() {
	    super.onLowMemory();
	    mMapView.onLowMemory();
	}

    public void markersCollector(String qrCodeId) {
        String result  = null;
    	try {
            Class.forName("com.mysql.jdbc.Driver");
            /*Specifications of the connection to the DB*/
            Connection con = DriverManager.getConnection(url, user, pass);
            result = "Database connection success\n";
     
            Statement st = con.createStatement();
            /*Basic sql query with qrCodeId as parameter of choice*/
            String query="select * from marker where qr_code_id = '"+ qrCodeId +"'";
            /*Execution of the query*/
            ResultSet rs = st.executeQuery(query);
            /*Expression to confirm that the connection to the db is started*/
            Toast.makeText(getActivity(), "Mes Lieux chargées! Si la mappe est vide, réessayez le scan du qrCode", Toast.LENGTH_LONG).show();
            ResultSetMetaData rsmd = rs.getMetaData();
            /*Parsing of each column of the table received. In our case:
             * 1)is the key identifier generated by the db
             * 2)is the description/commentary added by the web platform
             * 3)is latitude
             * 4)is longitude
             * 5)is the qrCodeId
             * */
            while(rs.next()) {
                LatLng latLng = null;
            	result += rsmd.getColumnName(1) + ": " + rs.getInt(1) + "\n";
            	result += rsmd.getColumnName(2) + ": " + rs.getString(2) + "\n";
            	result += rsmd.getColumnName(3) + ": " + rs.getDouble(3) + "\n";
            	result += rsmd.getColumnName(4) + ": " + rs.getDouble(4) + "\n";
            	result += rsmd.getColumnName(5) + ": " + rs.getString(5) + "\n";
            	/*creation of a latLng for each line of the table*/
                latLng = new LatLng(rs.getDouble(3),rs.getDouble(4));
                if(null == googleMap) {
                    throw new NullPointerException("map is null");
                }
                /*Call for getAddress() in main activity to retrieve the the address of each line*/
                String address =MainActivity.getAddress(getActivity(),rs.getDouble(3), rs.getDouble(4));
                /*Add a marker for each line received. title will show the address of getAddress() method, snippet will show the description in point 2 defined before */
                googleMap.addMarker(new MarkerOptions()
                        .title(address)
                        .snippet(rs.getString(2))
                        .position(latLng)
                );
            }
            /*Here we are just keeping the center of view on Geneva*/
            LatLng pos = new LatLng(46.201695904168325, 6.140153110027313);
            CameraPosition cameraPosition = new CameraPosition.Builder()
            .target(pos).zoom(12).build();
            googleMap.animateCamera(CameraUpdateFactory
            .newCameraPosition(cameraPosition));
        }
        catch(Exception e) {
            e.printStackTrace();
            Log.e("DB", result);
        }   
    }
}
